__1.__ Решить систему уравнений методом Гаусса:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$


$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$

$\Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -2 & 0 & 13\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
0\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
2 & 0 & -2 & 9\\ 
0 & -2 & 0 & 13\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
0\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
2 & 0 & 0 & 6\\ 
0 & -2 & 0 & 13\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-4\\ 
0\\
4
\end{matrix}
\end{pmatrix} \Rightarrow$

$\Rightarrow \begin{cases}
x_1 = -3x_4 - 2\\
x_2 = 13/2x_4\\
x_3 = 3/2x_4 - 2
\end{cases}$ 




Получили бесконечное количество решений.

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [73]:
import numpy as np

In [74]:
np.set_printoptions()
def solvable(m):
    if np.linalg.matrix_rank(m) == np.linalg.matrix_rank(m[:,:-1]) == len(m[0]) - 1:
        print('Solvable system, only one solution.')
    elif np.linalg.matrix_rank(m) == np.linalg.matrix_rank(m[:,:-1]) < len(m[0]) - 1:
        print('Solvable system, infinite quantity of solutions.')
    else:
        print('Unsolvable system.')


a = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
b = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
c = np.array([[1, 2, 5, 4], [3 , 1, -8, -2]])
print(f'system a)\n {a}')
solvable(a)
print(f'\nsystem b)\n {b}')
solvable(b)
print(f'\nsystem c)\n {c}')
solvable(c)

system a)
 [[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Solvable system, only one solution.

system b)
 [[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Unsolvable system.

system c)
 [[ 1  2  5  4]
 [ 3  1 -8 -2]]
Solvable system, infinite quantity of solutions.


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$

In [75]:
a = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print(a,'\n')
solvable(a)

[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]] 

Solvable system, only one solution.


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
3 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b -2a\\
c -3a
\end{matrix}
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a -2b 
\end{matrix}
\end{pmatrix} \Rightarrow$
$c + a - 2b \neq 0$ - в этом случае система несовместна, если = 0 то совместна. проверим e = (а, b, c) = (1, 3, 1) и e' = (а, b, c) = (1, 1, 1)

In [76]:
a = np.array([[1, 2, 3, 1], [4, 5, 6, 3], [7, 8, 9, 1]])
a1 = np.array([[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]])
print(np.linalg.matrix_rank(a))
solvable(a)
print(np.linalg.matrix_rank(a1))
solvable(a1)

3
Unsolvable system.
2
Solvable system, infinite quantity of solutions.


__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [77]:
import numpy as np
from numpy.linalg import det
from copy import deepcopy

def cramer(a, b):
    det_a = det(a)
    det_a_i = []
    for i in range(len(a[0])):
        c = deepcopy(a)
        c[:, i] = b
        det_a_i.append(det(c))
    for i, det_i in enumerate(det_a_i):
        print(f'x{i+1} = {det_a/det_i}')

a1 = np.array([[1, -2], [3, -4]])
b1 = np.array([1, 7])

a2 = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b2 = np.array([10, -2, 1])
print('Task a)')
cramer(a1, b1)
print('Task b)')
cramer(a2, b2)


Task a)
x1 = 0.20000000000000007
x2 = 0.5000000000000002
Task b)
x1 = 0.4999999999999995
x2 = -0.9999999999999992
x3 = 1.0


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}\Rightarrow$

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix} \Rightarrow$
$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix} = U$

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix} \Rightarrow
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix} = L$


   
 

  б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \Rightarrow$

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix} \Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} \Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}=U$

$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix} \Rightarrow
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix} \Rightarrow
\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix} = L$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$


In [78]:
from scipy.linalg import lu_solve, lu_factor
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
lu, piv = lu_factor(a)
x = lu_solve((lu, piv), b)
print(x)

[-1.  0.  1.]


__4*.__ Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

In [79]:
from scipy.linalg import cho_factor, cho_solve
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
c, low = cho_factor(a)
b = np.array([531, -460, 193])
x = cho_solve((c, low), b)
print(x)

[ 6. -5. -4.]


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

LU

In [80]:
def mine_lu(a):
    #return L, U matrixes
    a = np.array(a, dtype='float64')
    length = len(a)
    b = np.eye(length)
    p = np.eye(length)
    for j in range(0, length-1):
        for i in range(j + 1, length):
            b[i,j] = a[i,j] / a[j][j]            
            a[i,:] =  a[i,:] - a[i,j] / a[j][j] * a[j,:]        
    return b, a           
        
def solve_lu(a, b):
    l, u = mine_lu(a)
    length = len(l)
    y = np.concatenate([l, b.reshape(3,1)], axis = 1)
    for j in range(0, length-1):
        for i in range(j + 1, length):            
            y[i,:] =  y[i,:] - y[i,j] / y[j][j] * y[j,:]
    y = y[:,-1]
    x = np.concatenate([u, y.reshape(3,1)], axis = 1)
    length = len(x[0])
    for j in range(-2, - length , -1):
        for i in range(j, -length , -1):            
            x[i,:] =  x[i,:] - x[i,j] / x[j+1][j] * x[j+1,:]
    x_1 = [l[-1]/l[i] for i, l in enumerate(x)]

    return x_1


a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

solve_lu(a, b)

[6.0, -5.0, -4.0]

Если диагональный элемент станет равным 0, то алгоритм накроется, но сейчас уже не успею дописать матрицу перемещения строк местами. по сути надо будет придумать матрицу домнажая на которую х и b мы будем получать одинаковое перемещение строк. скорей всего это единичная матрица в которой нужно менять столбцы так же ка ки строки в основной матрице.